('kits' asFilename construct: 'Core.kit') fileIn !
('kits' asFilename construct: 'Compiler.kit') fileIn !
('kits' asFilename construct: 'CoreUI.kit') fileIn !
('kits' asFilename construct: 'Canvas Window.kit') fileIn !
('kits' asFilename construct: 'Development Tools.kit') fileIn !
('kits' asFilename construct: 'Other.kit') fileIn !
('kits' asFilename construct: 'String Art.kit') fileIn !
('kits' asFilename construct: 'Tests.kit') fileIn !
